// Host-side WIT bindings generated by `wasmtime::component::bindgen!`.
// Each world is namespaced in its own module to prevent the three
// bindgen! invocations from generating conflicting `exports` / `zeroclaw`
// module names in the same scope.
// These are internal to the `component` module — consumers use the adapter
// structs (`ComponentTool`, `ComponentMemory`, `ComponentChannel`) instead.

pub mod tool {
    wasmtime::component::bindgen!({ world: "tool-plugin",    path: "../../wit/v0"});
}
pub mod memory {
    wasmtime::component::bindgen!({ world: "memory-plugin",  path: "../../wit/v0" });
}
pub mod channel {
    wasmtime::component::bindgen!({ world: "channel-plugin", path: "../../wit/v0" });
}
